# Main scene file for our game
[[entities]]
name = "World"
  [entities.components.Tilemap]
  mapFile = "res/maps/level1.tmx"

[[entities]]
name = "Player"

  [entities.components.Transform]
  position = [640.0, 360.0]
  scale = [2.0, 2.0]

  [entities.components.Sprite]
  assetId = "player"
  isAnimated = true
  sortingLayer = 0      # 0 is our 'world' or 'player' layer
  orderInLayer = 10     # A value to sort within the layer

  [entities.components.PlayerControl]
  # Tag component

  [entities.components.Movement]
  speed = 200.0

  [entities.components.Intent]
  # Tag component

  [entities.components.Blackboard]
  # Empty for now, will be populated by systems

[[entities]]
name = "Camera"

  [entities.components.Transform]
  # Initial position doesn't matter, will be snapped to target.
  position = [0.0, 0.0]

  [entities.components.Camera]
  # Tag component

  [entities.components.Blackboard]
  cameraTarget = "Player" # Reference by name
  followSpeed = 12.0
  deadZoneRadius = 2.0
